[ 2025-04-14 18:19:58,558 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser/font.css
[ 2025-04-14 18:20:00,493 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminauser/
[ 2025-04-14 18:20:02,418 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminvivek/font.css
[ 2025-04-14 18:20:05,284 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser1/font.css
[ 2025-04-14 18:20:07,277 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminusera/
[ 2025-04-14 18:20:09,586 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser/font.css
[ 2025-04-14 18:20:11,681 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser1/font.css
[ 2025-04-14 18:20:15,066 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser/font.css
[ 2025-04-14 18:20:17,591 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminauser/
[ 2025-04-14 18:20:24,435 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminvivek/font.css
[ 2025-04-14 18:20:26,930 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser1/font.css
[ 2025-04-14 18:20:29,420 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-admintestuser/font.css
[ 2025-04-14 18:20:34,204 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminvvk/font.css
[ 2025-04-14 18:20:38,436 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminuser/font.css
[ 2025-04-14 18:20:39,884 ] 248 django.request - WARNING - Not Found: /admin_panel/user-profile-adminauser/
[ 2025-04-14 18:21:00,933 ] 248 django.request - WARNING - Not Found: /font.css
[ 2025-04-14 18:21:06,120 ] 248 django.request - WARNING - Not Found: /posts/font.css
[ 2025-04-14 18:21:11,121 ] 248 django.request - WARNING - Not Found: /posts/post/7/font.css
[ 2025-04-14 18:21:31,107 ] 248 django.request - WARNING - Not Found: /profile/user/font.css
[ 2025-04-14 18:21:32,423 ] 248 django.request - WARNING - Not Found: /edit/font.css
[ 2025-04-14 18:21:34,602 ] 248 django.request - WARNING - Not Found: /profile/user/font.css
[ 2025-04-14 18:21:37,268 ] 248 django.request - WARNING - Not Found: /posts/font.css
[ 2025-04-14 18:23:39,333 ] 248 django.request - WARNING - Not Found: /posts/create/font.css
[ 2025-04-14 18:23:47,847 ] 248 django.request - WARNING - Not Found: /posts/my-posts/
[ 2025-04-14 18:23:53,573 ] 248 django.request - WARNING - Not Found: /posts/my-posts/1/font.css
[ 2025-04-14 18:23:56,943 ] 248 django.request - WARNING - Not Found: /posts/my-posts/2/font.css
[ 2025-04-14 18:24:07,505 ] 248 django.request - ERROR - Internal Server Error: /posts/delete-post/1/
Traceback (most recent call last):
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: my_posts() got an unexpected keyword argument 'post_id'
[ 2025-04-14 18:24:11,033 ] 248 django.request - WARNING - Not Found: /posts/my-posts/2/font.css
[ 2025-04-14 18:24:12,445 ] 248 django.request - ERROR - Internal Server Error: /posts/delete-post/1/
Traceback (most recent call last):
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: my_posts() got an unexpected keyword argument 'post_id'
[ 2025-04-14 18:24:14,077 ] 248 django.request - WARNING - Not Found: /posts/my-posts/2/font.css
[ 2025-04-14 18:27:59,673 ] 248 django.request - ERROR - Internal Server Error: /posts/my-posts/2/
Traceback (most recent call last):
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vivek\Desktop\Projects\Cyber Guardia\Cyber-Bullying-Detection\posts\views.py", line 101, in my_posts
    return render(request, 'posts/my_posts.html', {'my_posts':my_posts})
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'my_posts' with no arguments not found. 1 pattern(s) tried: ['posts/my\\-posts/(?P<user_id>[0-9]+)/\\Z']
